export const GET_OPEN_WEATHER_REQUEST_ACTION = 'GET_OPEN_WEATHER_REQUEST_ACTION';
export const GET_OPEN_WEATHER_SUCCESS_ACTION = 'GET_OPEN_WEATHER_SUCCESS_ACTION';
export const GET_OPEN_WEATHER_FAIL_ACTION = 'GET_OPEN_WEATHER_FAIL_ACTION';


export const GET_STORM_REQUEST_ACTION = 'GET_STORM_REQUEST_ACTION';
export const GET_STORM_SUCCESS_ACTION = 'GET_STORM_SUCCESS_ACTION';
export const GET_STORM_FAIL_ACTION = 'GET_STORM_FAIL_ACTION';

export const GET_EVENTS_REQUEST_ACTION = 'GET_EVENTS_REQUEST_ACTION';
export const GET_EVENTS_SUCCESS_ACTION = 'GET_EVENTS_SUCCESS_ACTION';
export const GET_EVENTS_FAIL_ACTION = 'GET_EVENTS_FAIL_ACTION';
