export const GET_OPEN_WEATHER_REQUEST_ACTION = 'GET_OPEN_WEATHER_REQUEST_ACTION';
export const GET_OPEN_WEATHER_SUCCESS_ACTION = 'GET_OPEN_WEATHER_SUCCESS_ACTION';
export const GET_OPEN_WEATHER_FAIL_ACTION = 'GET_OPEN_WEATHER_FAIL_ACTION';
